version: '3.8'

networks:
  decky-network:
    driver: bridge

services:
  # --- Infrastructure ---
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - decky-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - decky-network
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - decky-network

  # --- Microservices ---
  user-auth:
    build:
      context: ./user-auth
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - decky-network
    ports:
      - "8081:8081"

  deck-service:
    build:
      context: ./deck-service
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - decky-network
    ports:
      - "8080:8080"

  today-session-service:
    build:
      context: ./today-session-service
      dockerfile: Dockerfile
    depends_on:
      - redis
      - deck-service
    env_file:
      - .env
    environment:
      - SERVER_PORT=8082
      - DECK_SERVICE_URL=http://deck-service:8080
    networks:
      - decky-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - user-auth
      - deck-service
      - today-session-service
    env_file:
      - .env
    environment:
      - USER_AUTH_URI=http://user-auth:8081
      - DECK_SERVICE_URI=http://deck-service:8080
      - TODAY_SESSION_SERVICE_URI=http://today-session-service:8082
    ports:
      - "8083:8083"
    networks:
      - decky-network

volumes:
  mongo_data:
  postgres_data: