server:
  port: 8083

spring:
  application:
    name: decky
  jwt:
    secret: ${JWT_SECRET:default_secret_for_local_dev}
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-auth
          uri: http://user-auth:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            
        - id: deck-service
          uri: http://deck-service:8080
          predicates:
            - Path=/api/flashcards/**
          filters:
            - StripPrefix=1
            
        - id: today-session-service
          uri: http://today-session-service:8080
          predicates:
            - Path=/api/sessions/**
          filters:
            - StripPrefix=1
